POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "htet",
  "password": 123,
  "age": 23
}

###
GET http://localhost:3000/user/1/posts/1001/comments

###
GET http://localhost:3000/search?userId=1&password=123

###
GET http://localhost:3000/posts

